{
	"Service": "/FieldServiceNotification/Services/SampleServiceV2.service",
	"DefiningRequests": [{
		"Name": "Customers",
		"Query": "Customers"
	}, {
		"Name": "SalesOrderItems",
		"Query": "SalesOrderItems"
	}, {
		"Name": "SalesOrderHeaders",
		"Query": "SalesOrderHeaders"
	}],
	"_Type": "Action.Type.OfflineOData.Download",
	"ActionResult": {
		"_Name": "sync"
	},
	"OnFailure": "/FieldServiceNotification/Actions/Service/SyncFailureMessage.action"
}